# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'c:\Users\wzb\Desktop\file\06191111.ui'
#
# Created by: PyQt5 UI code generator 5.9.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets
from PyQt5.QtWidgets import *
from PyQt5.QtCore import *
from PyQt5.QtGui import *
import action
import pandas as pd
import translatemedicine
from scipy import stats
import matplotlib.pyplot as plt
import numpy as np
import sys
sys.setrecursionlimit(100000)

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1027, 660)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.centralwidget)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.tabWidget = QtWidgets.QTabWidget(self.centralwidget)
        self.tabWidget.setToolTipDuration(-1)
        self.tabWidget.setTabShape(QtWidgets.QTabWidget.Rounded)
        self.tabWidget.setObjectName("tabWidget")
        self.tab = QtWidgets.QWidget()
        self.tab.setObjectName("tab")
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout(self.tab)
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.groupBox = QtWidgets.QGroupBox(self.tab)
        self.groupBox.setObjectName("groupBox")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.groupBox)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.pushButton = QtWidgets.QPushButton(self.groupBox)
        self.pushButton.setObjectName("pushButton")
        self.horizontalLayout_2.addWidget(self.pushButton)
        self.line = QtWidgets.QFrame(self.groupBox)
        self.line.setFrameShape(QtWidgets.QFrame.VLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setObjectName("line")
        self.horizontalLayout_2.addWidget(self.line)
        self.lineEdit = QtWidgets.QLineEdit(self.groupBox)
        self.lineEdit.setObjectName("lineEdit")
        self.horizontalLayout_2.addWidget(self.lineEdit)
        self.verticalLayout.addLayout(self.horizontalLayout_2)
        self.line_2 = QtWidgets.QFrame(self.groupBox)
        self.line_2.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_2.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_2.setObjectName("line_2")
        self.verticalLayout.addWidget(self.line_2)
        self.tableView = QtWidgets.QTableView(self.groupBox)
        self.tableView.setObjectName("tableView")
        self.verticalLayout.addWidget(self.tableView)
        self.verticalLayout_2.addLayout(self.verticalLayout)
        self.horizontalLayout_4.addWidget(self.groupBox)
        self.verticalLayout_5 = QtWidgets.QVBoxLayout()
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.groupBox_2 = QtWidgets.QGroupBox(self.tab)
        self.groupBox_2.setObjectName("groupBox_2")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(self.groupBox_2)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout()
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.comboBox = QtWidgets.QComboBox(self.groupBox_2)
        self.comboBox.setObjectName("comboBox")
        self.verticalLayout_3.addWidget(self.comboBox)
        self.textEdit = QtWidgets.QTextEdit(self.groupBox_2)
        self.textEdit.setObjectName("textEdit")
        self.verticalLayout_3.addWidget(self.textEdit)
        self.verticalLayout_4.addLayout(self.verticalLayout_3)
        self.verticalLayout_5.addWidget(self.groupBox_2)
        self.groupBox_3 = QtWidgets.QGroupBox(self.tab)
        self.groupBox_3.setObjectName("groupBox_3")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout(self.groupBox_3)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.label = QtWidgets.QLabel(self.groupBox_3)
        self.label.setText("")
        self.label.setObjectName("label")
        self.horizontalLayout_3.addWidget(self.label)
        self.verticalLayout_5.addWidget(self.groupBox_3)
        self.verticalLayout_5.setStretch(0, 1)
        self.verticalLayout_5.setStretch(1, 5)
        self.horizontalLayout_4.addLayout(self.verticalLayout_5)
        self.horizontalLayout_4.setStretch(0, 2)
        self.horizontalLayout_4.setStretch(1, 1)
        self.horizontalLayout_5.addLayout(self.horizontalLayout_4)
        self.tabWidget.addTab(self.tab, "")
        self.tab_2 = QtWidgets.QWidget()
        self.tab_2.setObjectName("tab_2")
        self.horizontalLayout_13 = QtWidgets.QHBoxLayout(self.tab_2)
        self.horizontalLayout_13.setObjectName("horizontalLayout_13")
        self.horizontalLayout_12 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_12.setObjectName("horizontalLayout_12")
        self.groupBox_4 = QtWidgets.QGroupBox(self.tab_2)
        self.groupBox_4.setObjectName("groupBox_4")
        self.verticalLayout_10 = QtWidgets.QVBoxLayout(self.groupBox_4)
        self.verticalLayout_10.setObjectName("verticalLayout_10")
        self.verticalLayout_7 = QtWidgets.QVBoxLayout()
        self.verticalLayout_7.setObjectName("verticalLayout_7")
        self.horizontalLayout_9 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_9.setObjectName("horizontalLayout_9")
        self.label_4 = QtWidgets.QLabel(self.groupBox_4)
        self.label_4.setObjectName("label_4")
        self.horizontalLayout_9.addWidget(self.label_4)
        self.comboBox_3 = QtWidgets.QComboBox(self.groupBox_4)
        self.comboBox_3.setObjectName("comboBox_3")
        self.horizontalLayout_9.addWidget(self.comboBox_3)
        self.pushButton_3 = QtWidgets.QPushButton(self.groupBox_4)
        self.pushButton_3.setObjectName("pushButton_3")
        self.horizontalLayout_9.addWidget(self.pushButton_3)
        self.horizontalLayout_9.setStretch(0, 2)
        self.horizontalLayout_9.setStretch(1, 4)
        self.horizontalLayout_9.setStretch(2, 1)
        self.verticalLayout_7.addLayout(self.horizontalLayout_9)
        self.textEdit_4 = QtWidgets.QTextEdit(self.groupBox_4)
        self.textEdit_4.setObjectName("textEdit_4")
        self.verticalLayout_7.addWidget(self.textEdit_4)
        self.verticalLayout_10.addLayout(self.verticalLayout_7)
        self.line_7 = QtWidgets.QFrame(self.groupBox_4)
        self.line_7.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_7.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_7.setObjectName("line_7")
        self.verticalLayout_10.addWidget(self.line_7)
        self.horizontalLayout_8 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_8.setObjectName("horizontalLayout_8")
        self.label_3 = QtWidgets.QLabel(self.groupBox_4)
        self.label_3.setToolTipDuration(0)
        self.label_3.setObjectName("label_3")
        self.horizontalLayout_8.addWidget(self.label_3)
        self.comboBox_2 = QtWidgets.QComboBox(self.groupBox_4)
        self.comboBox_2.setObjectName("comboBox_2")
        self.horizontalLayout_8.addWidget(self.comboBox_2)
        self.horizontalLayout_8.setStretch(1, 3)
        self.verticalLayout_10.addLayout(self.horizontalLayout_8)
        self.line_8 = QtWidgets.QFrame(self.groupBox_4)
        self.line_8.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_8.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_8.setObjectName("line_8")
        self.verticalLayout_10.addWidget(self.line_8)
        self.verticalLayout_9 = QtWidgets.QVBoxLayout()
        self.verticalLayout_9.setObjectName("verticalLayout_9")
        self.horizontalLayout_10 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_10.setObjectName("horizontalLayout_10")
        self.label_5 = QtWidgets.QLabel(self.groupBox_4)
        self.label_5.setToolTipDuration(0)
        self.label_5.setObjectName("label_5")
        self.horizontalLayout_10.addWidget(self.label_5)
        self.comboBox_4 = QtWidgets.QComboBox(self.groupBox_4)
        self.comboBox_4.setObjectName("comboBox_4")
        self.horizontalLayout_10.addWidget(self.comboBox_4)
        self.pushButton_4 = QtWidgets.QPushButton(self.groupBox_4)
        self.pushButton_4.setObjectName("pushButton_4")
        self.horizontalLayout_10.addWidget(self.pushButton_4)
        self.horizontalLayout_10.setStretch(0, 2)
        self.horizontalLayout_10.setStretch(1, 4)
        self.horizontalLayout_10.setStretch(2, 1)
        self.verticalLayout_9.addLayout(self.horizontalLayout_10)
        self.verticalLayout_9.setStretch(0, 1)
        self.verticalLayout_10.addLayout(self.verticalLayout_9)
        self.textEdit_11 = QtWidgets.QTextEdit(self.groupBox_4)
        self.textEdit_11.setObjectName("textEdit_11")
        self.verticalLayout_10.addWidget(self.textEdit_11)
        self.verticalLayout_8 = QtWidgets.QVBoxLayout()
        self.verticalLayout_8.setObjectName("verticalLayout_8")
        self.horizontalLayout_11 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_11.setObjectName("horizontalLayout_11")
        self.label_6 = QtWidgets.QLabel(self.groupBox_4)
        self.label_6.setToolTipDuration(0)
        self.label_6.setObjectName("label_6")
        self.horizontalLayout_11.addWidget(self.label_6)
        self.comboBox_5 = QtWidgets.QComboBox(self.groupBox_4)
        self.comboBox_5.setObjectName("comboBox_5")
        self.horizontalLayout_11.addWidget(self.comboBox_5)
        self.pushButton_5 = QtWidgets.QPushButton(self.groupBox_4)
        self.pushButton_5.setObjectName("pushButton_5")
        self.horizontalLayout_11.addWidget(self.pushButton_5)
        self.horizontalLayout_11.setStretch(0, 2)
        self.horizontalLayout_11.setStretch(1, 4)
        self.horizontalLayout_11.setStretch(2, 1)
        self.verticalLayout_8.addLayout(self.horizontalLayout_11)
        self.textEdit_12 = QtWidgets.QTextEdit(self.groupBox_4)
        self.textEdit_12.setObjectName("textEdit_12")
        self.verticalLayout_8.addWidget(self.textEdit_12)
        self.verticalLayout_8.setStretch(0, 1)
        self.verticalLayout_10.addLayout(self.verticalLayout_8)
        self.line_9 = QtWidgets.QFrame(self.groupBox_4)
        self.line_9.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_9.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_9.setObjectName("line_9")
        self.verticalLayout_10.addWidget(self.line_9)
        self.verticalLayout_10.setStretch(0, 3)
        self.verticalLayout_10.setStretch(2, 1)
        self.verticalLayout_10.setStretch(4, 2)
        self.horizontalLayout_12.addWidget(self.groupBox_4)
        self.groupBox_5 = QtWidgets.QGroupBox(self.tab_2)
        self.groupBox_5.setObjectName("groupBox_5")
        self.horizontalLayout_27 = QtWidgets.QHBoxLayout(self.groupBox_5)
        self.horizontalLayout_27.setObjectName("horizontalLayout_27")
        self.verticalLayout_11 = QtWidgets.QVBoxLayout()
        self.verticalLayout_11.setObjectName("verticalLayout_11")
        self.horizontalLayout_26 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_26.setObjectName("horizontalLayout_26")
        self.pushButton_6 = QtWidgets.QPushButton(self.groupBox_5)
        self.pushButton_6.setObjectName("pushButton_6")
        self.horizontalLayout_26.addWidget(self.pushButton_6)
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_26.addItem(spacerItem)
        self.verticalLayout_11.addLayout(self.horizontalLayout_26)
        self.textEdit_5 = QtWidgets.QTextEdit(self.groupBox_5)
        self.textEdit_5.setObjectName("textEdit_5")
        self.verticalLayout_11.addWidget(self.textEdit_5)
        self.horizontalLayout_25 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_25.setObjectName("horizontalLayout_25")
        self.pushButton_7 = QtWidgets.QPushButton(self.groupBox_5)
        self.pushButton_7.setObjectName("pushButton_7")
        self.horizontalLayout_25.addWidget(self.pushButton_7)
        self.label_18 = QtWidgets.QLabel(self.groupBox_5)
        self.label_18.setText("")
        self.label_18.setObjectName("label_18")
        self.horizontalLayout_25.addWidget(self.label_18)
        self.pushButton_8 = QtWidgets.QPushButton(self.groupBox_5)
        self.pushButton_8.setObjectName("pushButton_8")
        self.horizontalLayout_25.addWidget(self.pushButton_8)
        self.horizontalLayout_25.setStretch(1, 3)
        self.verticalLayout_11.addLayout(self.horizontalLayout_25)
        self.horizontalLayout_27.addLayout(self.verticalLayout_11)
        self.horizontalLayout_12.addWidget(self.groupBox_5)
        self.horizontalLayout_12.setStretch(0, 1)
        self.horizontalLayout_12.setStretch(1, 3)
        self.horizontalLayout_13.addLayout(self.horizontalLayout_12)
        self.tabWidget.addTab(self.tab_2, "")
        self.tab_3 = QtWidgets.QWidget()
        self.tab_3.setObjectName("tab_3")
        self.horizontalLayout_7 = QtWidgets.QHBoxLayout(self.tab_3)
        self.horizontalLayout_7.setObjectName("horizontalLayout_7")
        self.verticalLayout_6 = QtWidgets.QVBoxLayout()
        self.verticalLayout_6.setObjectName("verticalLayout_6")
        self.label_2 = QtWidgets.QLabel(self.tab_3)
        self.label_2.setObjectName("label_2")
        self.verticalLayout_6.addWidget(self.label_2)
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        self.textEdit_2 = QtWidgets.QTextEdit(self.tab_3)
        self.textEdit_2.setObjectName("textEdit_2")
        self.horizontalLayout_6.addWidget(self.textEdit_2)
        self.pushButton_2 = QtWidgets.QPushButton(self.tab_3)
        self.pushButton_2.setObjectName("pushButton_2")
        self.horizontalLayout_6.addWidget(self.pushButton_2)
        self.textEdit_3 = QtWidgets.QTextEdit(self.tab_3)
        self.textEdit_3.setObjectName("textEdit_3")
        self.horizontalLayout_6.addWidget(self.textEdit_3)
        self.verticalLayout_6.addLayout(self.horizontalLayout_6)
        self.horizontalLayout_7.addLayout(self.verticalLayout_6)
        self.tabWidget.addTab(self.tab_3, "")
        self.tab_4 = QtWidgets.QWidget()
        self.tab_4.setObjectName("tab_4")
        self.horizontalLayout_24 = QtWidgets.QHBoxLayout(self.tab_4)
        self.horizontalLayout_24.setObjectName("horizontalLayout_24")
        self.groupBox_6 = QtWidgets.QGroupBox(self.tab_4)
        self.groupBox_6.setObjectName("groupBox_6")
        self.verticalLayout_13 = QtWidgets.QVBoxLayout(self.groupBox_6)
        self.verticalLayout_13.setObjectName("verticalLayout_13")
        self.verticalLayout_12 = QtWidgets.QVBoxLayout()
        self.verticalLayout_12.setObjectName("verticalLayout_12")
        self.horizontalLayout_14 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_14.setObjectName("horizontalLayout_14")
        self.label_9 = QtWidgets.QLabel(self.groupBox_6)
        self.label_9.setObjectName("label_9")
        self.horizontalLayout_14.addWidget(self.label_9)
        self.comboBox_6 = QtWidgets.QComboBox(self.groupBox_6)
        self.comboBox_6.setObjectName("comboBox_6")
        self.horizontalLayout_14.addWidget(self.comboBox_6)
        self.horizontalLayout_14.setStretch(0, 1)
        self.horizontalLayout_14.setStretch(1, 3)
        self.verticalLayout_12.addLayout(self.horizontalLayout_14)
        self.horizontalLayout_15 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_15.setObjectName("horizontalLayout_15")
        self.label_10 = QtWidgets.QLabel(self.groupBox_6)
        self.label_10.setObjectName("label_10")
        self.horizontalLayout_15.addWidget(self.label_10)
        self.textEdit_6 = QtWidgets.QTextEdit(self.groupBox_6)
        self.textEdit_6.setObjectName("textEdit_6")
        self.horizontalLayout_15.addWidget(self.textEdit_6)
        self.horizontalLayout_15.setStretch(0, 1)
        self.horizontalLayout_15.setStretch(1, 3)
        self.verticalLayout_12.addLayout(self.horizontalLayout_15)
        self.pushButton_9 = QtWidgets.QPushButton(self.groupBox_6)
        self.pushButton_9.setObjectName("pushButton_9")
        self.verticalLayout_12.addWidget(self.pushButton_9)
        self.horizontalLayout_16 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_16.setObjectName("horizontalLayout_16")
        self.label_11 = QtWidgets.QLabel(self.groupBox_6)
        self.label_11.setObjectName("label_11")
        self.horizontalLayout_16.addWidget(self.label_11)
        self.textEdit_7 = QtWidgets.QTextEdit(self.groupBox_6)
        self.textEdit_7.setObjectName("textEdit_7")
        self.horizontalLayout_16.addWidget(self.textEdit_7)
        self.horizontalLayout_16.setStretch(0, 1)
        self.horizontalLayout_16.setStretch(1, 3)
        self.verticalLayout_12.addLayout(self.horizontalLayout_16)
        self.verticalLayout_12.setStretch(0, 1)
        self.verticalLayout_12.setStretch(1, 1)
        self.verticalLayout_12.setStretch(3, 2)
        self.verticalLayout_13.addLayout(self.verticalLayout_12)
        self.horizontalLayout_24.addWidget(self.groupBox_6)
        self.groupBox_7 = QtWidgets.QGroupBox(self.tab_4)
        self.groupBox_7.setObjectName("groupBox_7")
        self.verticalLayout_18 = QtWidgets.QVBoxLayout(self.groupBox_7)
        self.verticalLayout_18.setObjectName("verticalLayout_18")
        self.verticalLayout_15 = QtWidgets.QVBoxLayout()
        self.verticalLayout_15.setObjectName("verticalLayout_15")
        self.horizontalLayout_17 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_17.setObjectName("horizontalLayout_17")
        self.label_16 = QtWidgets.QLabel(self.groupBox_7)
        self.label_16.setObjectName("label_16")
        self.horizontalLayout_17.addWidget(self.label_16)
        self.comboBox_7 = QtWidgets.QComboBox(self.groupBox_7)
        self.comboBox_7.setObjectName("comboBox_7")
        self.horizontalLayout_17.addWidget(self.comboBox_7)
        self.horizontalLayout_17.setStretch(0, 1)
        self.horizontalLayout_17.setStretch(1, 3)
        self.verticalLayout_15.addLayout(self.horizontalLayout_17)
        self.horizontalLayout_18 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_18.setObjectName("horizontalLayout_18")
        self.verticalLayout_14 = QtWidgets.QVBoxLayout()
        self.verticalLayout_14.setObjectName("verticalLayout_14")
        self.label_13 = QtWidgets.QLabel(self.groupBox_7)
        self.label_13.setToolTip("")
        self.label_13.setObjectName("label_13")
        self.verticalLayout_14.addWidget(self.label_13)
        self.verticalLayout_14.setStretch(0, 3)
        self.horizontalLayout_18.addLayout(self.verticalLayout_14)
        self.textEdit_8 = QtWidgets.QTextEdit(self.groupBox_7)
        self.textEdit_8.setObjectName("textEdit_8")
        self.horizontalLayout_18.addWidget(self.textEdit_8)
        self.horizontalLayout_18.setStretch(0, 1)
        self.horizontalLayout_18.setStretch(1, 3)
        self.verticalLayout_15.addLayout(self.horizontalLayout_18)
        self.horizontalLayout_20 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_20.setObjectName("horizontalLayout_20")
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_20.addItem(spacerItem1)
        self.checkBox_2 = QtWidgets.QCheckBox(self.groupBox_7)
        self.checkBox_2.setObjectName("checkBox_2")
        self.horizontalLayout_20.addWidget(self.checkBox_2)
        self.checkBox = QtWidgets.QCheckBox(self.groupBox_7)
        self.checkBox.setObjectName("checkBox")
        self.horizontalLayout_20.addWidget(self.checkBox)
        self.horizontalLayout_20.setStretch(0, 1)
        self.horizontalLayout_20.setStretch(1, 1)
        self.horizontalLayout_20.setStretch(2, 1)
        self.verticalLayout_15.addLayout(self.horizontalLayout_20)
        self.horizontalLayout_19 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_19.setObjectName("horizontalLayout_19")
        self.label_14 = QtWidgets.QLabel(self.groupBox_7)
        self.label_14.setObjectName("label_14")
        self.horizontalLayout_19.addWidget(self.label_14)
        self.textEdit_9 = QtWidgets.QTextEdit(self.groupBox_7)
        self.textEdit_9.setObjectName("textEdit_9")
        self.horizontalLayout_19.addWidget(self.textEdit_9)
        self.horizontalLayout_19.setStretch(0, 1)
        self.horizontalLayout_19.setStretch(1, 3)
        self.verticalLayout_15.addLayout(self.horizontalLayout_19)
        self.verticalLayout_18.addLayout(self.verticalLayout_15)
        self.horizontalLayout_24.addWidget(self.groupBox_7)
        self.groupBox_8 = QtWidgets.QGroupBox(self.tab_4)
        self.groupBox_8.setObjectName("groupBox_8")
        self.verticalLayout_17 = QtWidgets.QVBoxLayout(self.groupBox_8)
        self.verticalLayout_17.setObjectName("verticalLayout_17")
        self.verticalLayout_16 = QtWidgets.QVBoxLayout()
        self.verticalLayout_16.setObjectName("verticalLayout_16")
        self.horizontalLayout_21 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_21.setObjectName("horizontalLayout_21")
        self.label_15 = QtWidgets.QLabel(self.groupBox_8)
        self.label_15.setObjectName("label_15")
        self.horizontalLayout_21.addWidget(self.label_15)
        self.comboBox_8 = QtWidgets.QComboBox(self.groupBox_8)
        self.comboBox_8.setObjectName("comboBox_8")
        self.horizontalLayout_21.addWidget(self.comboBox_8)
        self.horizontalLayout_21.setStretch(0, 1)
        self.horizontalLayout_21.setStretch(1, 3)
        self.verticalLayout_16.addLayout(self.horizontalLayout_21)
        self.horizontalLayout_22 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_22.setObjectName("horizontalLayout_22")
        self.label_17 = QtWidgets.QLabel(self.groupBox_8)
        self.label_17.setObjectName("label_17")
        self.horizontalLayout_22.addWidget(self.label_17)
        self.comboBox_9 = QtWidgets.QComboBox(self.groupBox_8)
        self.comboBox_9.setObjectName("comboBox_9")
        self.horizontalLayout_22.addWidget(self.comboBox_9)
        self.horizontalLayout_22.setStretch(0, 1)
        self.horizontalLayout_22.setStretch(1, 3)
        self.verticalLayout_16.addLayout(self.horizontalLayout_22)
        self.pushButton_10 = QtWidgets.QPushButton(self.groupBox_8)
        self.pushButton_10.setObjectName("pushButton_10")
        self.verticalLayout_16.addWidget(self.pushButton_10)
        self.horizontalLayout_23 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_23.setObjectName("horizontalLayout_23")
        self.label_12 = QtWidgets.QLabel(self.groupBox_8)
        self.label_12.setObjectName("label_12")
        self.horizontalLayout_23.addWidget(self.label_12)
        self.textEdit_10 = QtWidgets.QTextEdit(self.groupBox_8)
        self.textEdit_10.setObjectName("textEdit_10")
        self.horizontalLayout_23.addWidget(self.textEdit_10)
        self.horizontalLayout_23.setStretch(0, 1)
        self.horizontalLayout_23.setStretch(1, 3)
        self.verticalLayout_16.addLayout(self.horizontalLayout_23)
        self.verticalLayout_17.addLayout(self.verticalLayout_16)
        self.horizontalLayout_24.addWidget(self.groupBox_8)
        self.tabWidget.addTab(self.tab_4, "")
        self.horizontalLayout.addWidget(self.tabWidget)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1027, 26))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.label_4.setBuddy(self.comboBox_3)
        self.label_3.setBuddy(self.comboBox_2)
        self.label_5.setBuddy(self.comboBox_2)
        self.label_6.setBuddy(self.comboBox_2)
        self.label_9.setBuddy(self.comboBox_6)

        self.retranslateUi(MainWindow)
        self.tabWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

        #action list
        self.pushButton.clicked.connect(self.openfile)
        self.pushButton_2.clicked.connect(self.translate)
    
        self.comboBox.activated.connect(self.normal_test)

        self.comboBox_3.activated.connect(lambda:self.tableonetext(self.comboBox_3,self.textEdit_4))
        self.pushButton_3.clicked.connect(lambda:self.clear(self.textEdit_4))

        self.comboBox_4.activated.connect(lambda:self.tableonetext(self.comboBox_4,self.textEdit_11))
        self.pushButton_4.clicked.connect(lambda:self.clear(self.textEdit_11))

        self.comboBox_5.activated.connect(lambda:self.tableonetext(self.comboBox_5,self.textEdit_12))
        self.pushButton_5.clicked.connect(lambda:self.clear(self.textEdit_12))

        self.pushButton_6.clicked.connect(self.tableone)
        self.pushButton_7.clicked.connect(self.save_path)
        self.pushButton_8.clicked.connect(self.save_file)

        self.comboBox_6.activated.connect(lambda:self.itemselect(self.comboBox_6,self.textEdit_6))
        self.comboBox_7.activated.connect(lambda:self.itemselect(self.comboBox_7,self.textEdit_8))

        self.pushButton_9.clicked.connect(self.chisqure)
        
        self.checkBox_2.toggled.connect(lambda:self.corrdata(self.checkBox_2))
        self.checkBox.toggled.connect(lambda:self.corrdata(self.checkBox))

        self.pushButton_10.clicked.connect(self.KWtext)



    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.groupBox.setTitle(_translate("MainWindow", "文件预览"))
        self.pushButton.setText(_translate("MainWindow", "打开文件"))
        self.groupBox_2.setTitle(_translate("MainWindow", "正态性检验"))
        self.groupBox_3.setTitle(_translate("MainWindow", "变量分布"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab), _translate("MainWindow", "Open"))
        self.groupBox_4.setTitle(_translate("MainWindow", "选择变量（*必选）"))
        self.label_4.setText(_translate("MainWindow", "统计变量"))
        self.pushButton_3.setText(_translate("MainWindow", "清空"))
        self.label_3.setToolTip(_translate("MainWindow", "<html><head/><body><p>选择分组变量：使得其他所有变量按照该分类变量分组统计。</p></body></html>"))
        self.label_3.setText(_translate("MainWindow", "分组变量*"))
        self.label_5.setToolTip(_translate("MainWindow", "<html><head/><body><p>选择分组变量：使得其他所有变量按照该分类变量分组统计。</p></body></html>"))
        self.label_5.setText(_translate("MainWindow", "非正太性"))
        self.pushButton_4.setText(_translate("MainWindow", "清空"))
        self.label_6.setToolTip(_translate("MainWindow", "<html><head/><body><p>选择分组变量：使得其他所有变量按照该分类变量分组统计。</p></body></html>"))
        self.label_6.setText(_translate("MainWindow", "分类变量"))
        self.pushButton_5.setText(_translate("MainWindow", "清空"))
        self.groupBox_5.setTitle(_translate("MainWindow", "Table1"))
        self.pushButton_6.setText(_translate("MainWindow", "生成 Table One"))
        self.pushButton_7.setText(_translate("MainWindow", "选择地址"))
        self.pushButton_8.setText(_translate("MainWindow", "保存"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_2), _translate("MainWindow", "Table One"))
        self.label_2.setText(_translate("MainWindow", "医学英语翻译，请保持网络畅通！"))
        self.pushButton_2.setText(_translate("MainWindow", "Go"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_3), _translate("MainWindow", "Translate"))
        self.groupBox_6.setTitle(_translate("MainWindow", "卡方"))
        self.label_9.setText(_translate("MainWindow", "选择变量"))
        self.label_10.setText(_translate("MainWindow", "已选择"))
        self.pushButton_9.setText(_translate("MainWindow", "计算"))
        self.label_11.setText(_translate("MainWindow", "结果"))
        self.groupBox_7.setTitle(_translate("MainWindow", "相关性"))
        self.label_16.setText(_translate("MainWindow", "选择变量"))
        self.label_13.setText(_translate("MainWindow", "已选择"))
        self.checkBox_2.setText(_translate("MainWindow", "pearson"))
        self.checkBox.setText(_translate("MainWindow", "spearman"))
        self.label_14.setText(_translate("MainWindow", "结果"))
        self.groupBox_8.setTitle(_translate("MainWindow", "K-W检验"))
        self.label_15.setText(_translate("MainWindow", "分组变量"))
        self.label_17.setText(_translate("MainWindow", "检验字段"))
        self.pushButton_10.setText(_translate("MainWindow", "计算"))
        self.label_12.setText(_translate("MainWindow", "结果"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_4), _translate("MainWindow", "Statistics"))

    def openfile(self):
        self.comboBox.clear()  
        self.comboBox_2.clear() 
        self.comboBox_3.clear() 
        self.comboBox_4.clear()
        self.comboBox_5.clear()
        self.comboBox_6.clear() 
        self.comboBox_7.clear()
        self.comboBox_8.clear()
        self.comboBox_9.clear()

        self.comboBox.setCurrentIndex(-1)
        self.comboBox_2.setCurrentIndex(-1)
        self.comboBox_3.setCurrentIndex(-1)
        self.comboBox_4.setCurrentIndex(-1)
        self.comboBox_5.setCurrentIndex(-1)
        self.comboBox_6.setCurrentIndex(-1)
        self.comboBox_7.setCurrentIndex(-1)
        self.comboBox_8.setCurrentIndex(-1)
        self.comboBox_9.setCurrentIndex(-1)
       
        openfile_name = QFileDialog.getOpenFileName(None,'选择文件','','Excel files(*.xlsx , *.xls);;CSV files(*.csv)')
        self.lineEdit.setText(openfile_name[0])
        self.path = openfile_name[0]
        if len(self.path) > 0:
            self.showdata()

    def showdata(self):
        if len(self.path) > 0:
            if self.path.endswith('csv'):
                self.data = pd.read_csv(self.path)
            elif self.path.endswith('xlsx') :
                self.data = pd.read_excel(self.path,sheet_name=0)               
            row = self.data.shape[0]
            col = self.data.shape[1]
            headers = self.data.columns.values.tolist()
            self.comboBox.addItems(headers)
            self.comboBox.setCurrentIndex(-1)
            self.comboBox_2.addItems(headers) 
            self.comboBox_2.setCurrentIndex(-1)
            self.comboBox_3.addItems(headers) 
            self.comboBox_3.setCurrentIndex(-1)
            self.comboBox_4.addItems(headers)
            self.comboBox_4.setCurrentIndex(-1)
            self.comboBox_5.addItems(headers)
            self.comboBox_5.setCurrentIndex(-1)
            self.comboBox_6.addItems(headers)
            self.comboBox_6.setCurrentIndex(-1)
            self.comboBox_7.addItems(headers)
            self.comboBox_7.setCurrentIndex(-1)
            self.comboBox_8.addItems(headers)
            self.comboBox_8.setCurrentIndex(-1)
            self.comboBox_9.addItems(headers)
            self.comboBox_9.setCurrentIndex(-1)
            #print(row,col,headers)
            self.csvModel = QStandardItemModel(row,col)
            self.csvModel.setHorizontalHeaderLabels(headers)
            self.tableView.setModel(self.csvModel)

            for i in range(row):
                for j in range(col):
                    item = QStandardItem(str(self.data.iloc[i,j]))
                    self.csvModel.setItem(i,j,item)
        else:
            pass
    
    def normal_test(self):
        plt.rcParams['font.sans-serif']=['SimHei']
        plt.rcParams['axes.unicode_minus'] = False
        Variable = self.comboBox.currentText()
        #print(Variable)
        self.label.clear()
        if len(Variable) > 0: 
            frame = self.data[Variable]
            try:
                result = stats.normaltest(frame)               
                if result[1]>0.05:
                    self.textEdit.setText(str(result)+'\n 符合正态性分布')
                else:
                    self.textEdit.setText(str(result)+'\n 不符合正态性分布')
                plt.figure(figsize=(3,4))
                image = plt.hist(frame,alpha=0.4)
                plt.xlabel(Variable)
                image = plt.savefig('1.png')
                self.label.setPixmap(QPixmap('1.png'))
            except:
                self.textEdit.setText('请检查数据是否合法！')
        else:
            pass

    def translate(self):     
        TR = translatemedicine.TranslateMedical()
        text = self.textEdit_2.toPlainText()
        tranlate = TR.run(text)
        self.textEdit_3.setText(tranlate)

    def tableonetext(self,combobox,textEdit):
        text = combobox.currentText()
        #print(text)
        if text not in textEdit.toPlainText().split():
            textEdit.insertPlainText(text+'\n')
        else:
            pass
    
    def clear(self,textEdit):
        textEdit.setText('')

    def tableone(self):
        import tableone 
        columns = self.textEdit_4.toPlainText().split()
        categorical = self.textEdit_12.toPlainText().split()
        groupby = self.comboBox_2.currentText().split()
        nonnormal = self.textEdit_11.toPlainText().split()
        try:
            self.mytable = tableone.TableOne(self.data, columns=columns, categorical=categorical, groupby=groupby, nonnormal=nonnormal,pval=True)
            self.textEdit_5.setLineWrapMode(QTextEdit.NoWrap)
            self.textEdit_5.setText(str(self.mytable.tabulate))
            
        except :
            #print(mytable.tabulate)
            self.textEdit_5.setText('请检查变量是否正确')
         
    def save_path(self):
        self.save_path = QFileDialog.getExistingDirectory()
        self.save_path = self.save_path + '/tableone.csv'
        #printprint(self.save_path)
        self.label_18.setText(self.save_path)

    def save_file(self):
        self.mytable.to_csv(self.save_path,encoding = 'utf-8-sig')
        QMessageBox.information(None, '','保存成功',QMessageBox.Yes )
    
    def itemselect(self,combobox,textEdit):
        items = textEdit.toPlainText().split()
        text = combobox.currentText()
        if text not in textEdit.toPlainText().split():
            if len(items) < 2 :
                textEdit.insertPlainText(text+'\n')
            else:
                textEdit.clear()
                textEdit.insertPlainText(items[1]+'\n')
                textEdit.insertPlainText(text+'\n')

    def chisqure(self):
        try:
            vas = self.textEdit_6.toPlainText().split()
            contingency_table = pd.crosstab(self.data[vas[0]],self.data[vas[1]],margins = True)
            f_obs = np.array([contingency_table.iloc[0][0:2].values,contingency_table.iloc[1][0:2].values])
            from scipy import stats
            result = stats.chi2_contingency(f_obs)[0:3]
            p_value = result[1]
            DF = result[2]
            self.textEdit_7.clear()
            self.textEdit_7.insertPlainText('交叉表：' + '\n' + str(contingency_table) + '\n')
            self.textEdit_7.insertPlainText('\np_value is : %.4f \n' %p_value)
            self.textEdit_7.insertPlainText('Degree of freedom is : %d \n' %DF)
        except :
            pass

    def corrdata(self,checkBox):  
        try:
            vas = self.textEdit_8.toPlainText().split()
            datasa = self.data[vas]
            fun = checkBox.text()
            if fun == 'pearson' :
                self.checkBox.setChecked(False) 
                result = datasa.corr(method='pearson')
            else:
                self.checkBox_2.setChecked(False)
                result = datasa.corr(method='spearman')
            self.textEdit_9.clear()    
            self.textEdit_9.setText(str(result))
        except :
            pass

    def KWtext(self):
        try:
            classname0 = self.comboBox_8.currentText()
            conti = self.comboBox_9.currentText()
            classname = self.data[classname0].drop_duplicates().values
            n = len(classname)
            kwlist=[]
            for i in classname:
                index = self.data[classname0] == i
                lianxu = list(self.data[conti][index])
                kwlist.append(lianxu)
            from scipy import stats
            if n == 3:
                result = stats.stats.kruskal(kwlist[0],kwlist[1],kwlist[2])
            elif n ==4:
                result = stats.stats.kruskal(kwlist[0],kwlist[1],kwlist[2],kwlist[3])
            elif n ==5:
                result = stats.stats.kruskal(kwlist[0],kwlist[1],kwlist[2],kwlist[3],kwlist[4])
            else:
                pass

            self.textEdit_10.clear()
            self.textEdit_10.setText('\np_value is : %.4f \n' % result[1])
        except :
            self.textEdit_10.clear()
            self.textEdit_10.setText('输入数据格式有误')

    

if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())

